"""Initial Migration

Revision ID: 741111a72f52
Revises: 5a26904b5a0c
Create Date: 2020-12-08 17:59:32.556071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '741111a72f52'
down_revision = '5a26904b5a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('pitches', 'time')
    op.add_column('users', sa.Column('profile_pic_path', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.add_column('pitches', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'datetime')
    # ### end Alembic commands ###
